### ISSUE TITLE
Getting Build Docker Error

### ISSUE THREAD

**Issue by Alter-Nimbus** [Monadical-SAS/Morpheus#128]
I get a docker build error with the Firebase API key, no matter what i can't find its solution

This is the log

.32 Sentry Logger [warn]: No DSN provided, client will not do anything.
83.33 Sentry Logger [log]: Initializing SDK...
83.33 Sentry Logger [warn]: No DSN provided, client will not do anything.
83.33 Sentry Logger [log]: SDK successfully initialized
83.67 FirebaseError: Firebase: Error (auth/invalid-api-key).
83.67     at createErrorInternal (file:///app/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:490:40)
83.67     at _assert (file:///app/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:494:15)
83.67     at Component.instanceFactory (file:///app/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6506:9)
83.67     at Provider.getOrInitializeService (file:///app/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
83.67     at Provider.initialize (file:///app/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
83.67     at initializeAuth (file:///app/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:2943:27)
83.67     at getAuth (file:///app/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6567:18)
83.67     at /app/.next/server/chunks/774.js:877:68 {
83.67   code: 'auth/invalid-api-key',
83.67   customData: { appName: '[DEFAULT]' }
83.67 }
83.68
83.68 > Build error occurred
83.68 Error: Failed to collect page data for /imagine/upscaling
83.68     at /app/node_modules/next/dist/build/utils.js:955:15
83.68     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
83.68   type: 'Error'
83.68 }
83.83 error Command failed with exit code 1.
83.83 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install && yarn build" did not complete successfully: exit code: 1

Thank you for help!

**Comment by Alter-Nimbus** [comment]
Fixed with the Firebase issue, had to delete all images but i still get this last error

83.68 > Build error occurred
83.68 Error: Failed to collect page data for /imagine/upscaling
83.68 at /app/node_modules/next/dist/build/utils.js:955:15
83.68 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
83.68 type: 'Error'
83.68 }
83.83 error Command failed with exit code 1.
